spring.application.name=TeluskoDay4-3

server.servlet.context-path = /employeerecordapp

spring.mvc.view.prefix = /jspPages/
spring.mvc.view.suffix = .jsp

spring.datasource.url = jdbc:mysql://localhost:3306/db2025
spring.datasource.username = root
spring.datasource.password = abhi@123

spring.jpa.show-sql = true

