version: '3.8'

services:
  app:
    image: abhishek/demo1:rev1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springdaotestsm?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdaotestsm
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
